### ISSUE TITLE
Get Access to TARDIS

### ISSUE THREAD

**Issue by Roxerg** [Roxerg/miniblog#1]
Lets set up an environment on Tardis to test out and host our app for the time being. I have an account and I might get you forms to fill for your accounts (though it might be you need to deliver them in-person, not sure). 

It's pretty convenient because afaik setting up a (shitty) domain is really easy there.

**Comment by Roxerg** [comment]
https://tardis.ed.ac.uk/files/tardisform.pdf 

Print this, fill this. 

Then slide it under the door of the Tardis room.

I'll ask if it's possible to email these

**Comment by Roxerg** [comment]
I'll also look into giving access to a folder on Tardis somehow idk

**Comment by qaisjp** [comment]
Hi @Roxerg, @sBaidani, @kimbethstonehouse! 👋 
Welcome to the TARDIS community! 🎉

This looks like an interesting project.
We have been experimenting with online memberships so feel free to [sign up here](https://forms.office.com/Pages/ResponsePage.aspx?id=sAafLmkWiUWHiRCgaTTcYRwR2tSUF3ZPoaMqKa2XeyVUMDlQOFRKRkxYQUVNMlNDU1lRSzJCR0hEMCQlQCN0PWcu) (this link is for University of Edinburgh students only).

Depending on the nature of your project we can either show you where you can run your code or create a container for you to set up your own environment. Getting a subdomain like _workfloe.tardis.ed.ac.uk_ is totally doable 🙂

If you have questions feel free to reach out to myself or any of the people listed in the CC.

Best of luck with your project!

/cc @rphi @cazagen
