### ISSUE TITLE
Market Research

### ISSUE THREAD

**Issue by Roxerg** [Roxerg/miniblog#7]
yo we actually should try out a bunch of work apps.

Let's get a list going here of features we notice that are gr8 and what we think they lack.

Shit to check out:

- Wunderlist
- Todoist
- OmniFocus
- FlowTasks
- Toggl
- Trello
- G Tasks

add more.

Also we should check out apps on iOS if possible and see maybe android apps lack some features from those we could bring in to the market.

**Comment by sBaidani** [comment]
Toggl
Trello
Google Tasks

**Comment by sBaidani** [comment]
Let's just edit the issues for important updates rather than commenting lol
